#gcr.io/subtle-palisade-304316/github.com/paulentin/eduprj:$COMMIT_SHA
#docker build \
#-t gcr.io/subtle-palisade-304316/github.com/paulentin/eduprj:$COMMIT_SHA \
#.
steps:
  # Build Stage
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/subtle-palisade-304316/github.com/paulentin/eduprj:$COMMIT_SHA', '.']
